### ISSUE TITLE
No support for new Android plugin system in 3.2.2?

### ISSUE THREAD

**Issue by tolgakaranlik** [DrMoriarty/godot-facebook#10]
I suspect that when I get this error it should be because of the incompatibility with the new build system of Android which is introduced in Godot 3.2.2:

AttributeError: 'SConsEnvironment' object has no attribute 'android_add_dependency':
  File "D:\temp\godot-master\SConstruct", line 554:
    config.configure(env)
  File "modules/GodotFacebook\config.py", line 12:
    env.android_add_dependency("implementation 'com.facebook.android:facebook-android-sdk:5.+'")

Please tell me that I am not right :) No compatibility with the 3.2.2's new Android plugin system?

**Comment by DrMoriarty** [comment]
Plugin updated and using now new plugin management system.
