### ISSUE TITLE
Plugin does not load on Android [Godot 3.2.3]

### ISSUE THREAD

**Issue by threethan** [DrMoriarty/godot-facebook#11]
Installed via NativeLib. 
Android is active. AppId is set. Both nativelib and nativelib-export are enabled.

Issue: The singleton "GodotFacebook" does not exist, and therefore the plugin does not function.

I have tried both a streamed export from the editor, and creating an APK.
Android is enabled in NativeLib. Custom build is enabled, although no custom build plugins show up.

**Comment by threethan** [comment]
I'm using windows - it seems like the *actual* problem is that the NativeLib UI does not work at all on windows.

**Comment by threethan** [comment]
Closing this and submitting issue to NativeLib

**Comment by DrMoriarty** [comment]
@threethan Could you upload your APK file?
