### ISSUE TITLE
Will this also work for facebook ads manager?

### ISSUE THREAD

**Issue by SoloCarryGuy** [DrMoriarty/godot-facebook#15]
I wanted to know will this work for event logging with Facebook ads manager.
![Screenshot (269)](https://user-images.githubusercontent.com/44634090/105951639-632a2780-6096-11eb-8aa8-c17eb4bc0def.png)

**Comment by DrMoriarty** [comment]
@SoloCarryGuy This plugin don't add dependency to facebook-marketing, but you can add it manually. For example see how https://github.com/DrMoriarty/godot-firebase-crashlytics adds dependency to the crashlytics library.

**Comment by SoloCarryGuy** [comment]
@DrMoriarty I am just a beginner with a few months of coding experience only in godot. I checked out the crashlytics link. And, I have tried to do it with some documentaion from facebook. [this is done by you](https://developers.facebook.com/docs/app-events/getting-started-app-events-android#1--integrate-the-facebook-sdk-in-your-android-app) from what I understand. I have tried to implement [this](https://developers.facebook.com/docs/app-events/codeless-app-events#android-integration) .This is the code I end up with 
gradle.conf looks like this: 
```
[buildscript_repositories]

[buildscript_dependencies]

[allprojects_repositories]

[dependencies]
implementation 'com.facebook.android:facebook-android-sdk:5.+'
implementation 'com.facebook.android:facebook-marketing:[4,5)' 
implementation 'com.google.android.gms:play-services-ads:15.0.0'

[android_defaultconfig]

[global]
```

AndroidManifest.conf looks like this:
```
[user_permissions]
<uses-permission android:name="android.permission.INTERNET"/>

[application]
<activity android:name="com.facebook.FacebookActivity"
          android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"
          android:theme="@style/com_facebook_activity_theme" 
          android:label="@string/godot_project_name_string" />
<activity android:name="com.facebook.CustomTabActivity" android:exported="true"> 
          <intent-filter> 
                          <action android:name="android.intent.action.VIEW" /> 
                          <category android:name="android.intent.category.DEFAULT" /> 
                          <category android:name="android.intent.category.BROWSABLE" /> 
                          <data android:scheme="@string/fb_login_protocol_scheme" /> 
          </intent-filter> 
</activity>
          
<meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id" />
<meta-data android:name="com.facebook.sdk.CodelessDebugLogEnabled" android:value="true" />

[application_attribs]
```
Is this okay?

**Comment by DrMoriarty** [comment]
@SoloCarryGuy I think that you don't need AndroidManifest.conf at all. Only gradle.conf with dependencies.

**Comment by SoloCarryGuy** [comment]
So, what should I do to correct it? `implementation 'com.facebook.android:facebook-marketing:[4,5)'` This is the only dependency [here](https://developers.facebook.com/docs/app-events/codeless-app-events#android-integration)

**Comment by DrMoriarty** [comment]
yes

**Comment by SoloCarryGuy** [comment]
Okay. Thanks for the help.
