### ISSUE TITLE
Question: iOS Native x Browser?

### ISSUE THREAD

**Issue by dpensky** [DrMoriarty/godot-facebook#20]
~~1 - On iOS login with Facebook only works if the user is a registered developer/admin or a test user, and not some _normal_ Facebook user account. Facebook app is in "Live" Mode. After confirming/accepting the login on the Facebook screen, the login flow goes back to the first Facebook screen without giving an error or confirming the login. I'm missing something or this is expected while the iOS is not approved by Apple?~~ This started working alone.

2 - Even with a test user, login only works if user is connected on the web browser. Being connected only in the Facebook native iOS app does no work for me.

On Android, Plugin/Login works great in all cases (normal user, test user, native, browser)

3 - xcode debug console prints this message:
`2021-10-20 11:01:20.750944-0300 app-name[887:186720] FBSDKLog: fb-messenger-share-api is missing from your Info.plist under LSApplicationQueriesSchemes and is required.`
is this a problem?

Thanks for the work and effort!

**Comment by DrMoriarty** [comment]
I'm not sure
try to add to `/addons/nativelib-export/iOS/facebook-plugin.plist` 
```
<string>fb-messenger-share-api</string>
```
in the array

**Comment by dpensky** [comment]
> I'm not sure try to add to `/addons/nativelib-export/iOS/facebook-plugin.plist`
> 
> ```
> <string>fb-messenger-share-api</string>
> ```
> 
> in the array

This removed the console print, but didn't change apparently.

> 2 - Even with a test user, login only works if user is connected on the web browser. Being connected only in the Facebook native iOS app does no work for me.

This appears to be the default behavior on iOS.

Thanks for your reply. I will close this for now.
