### ISSUE TITLE
An error occurs with a global variable.

### ISSUE THREAD

**Issue by dbrova15** [DrMoriarty/godot-facebook#9]
I don’t understand how to set up a singleton.

![Screenshot_6](https://user-images.githubusercontent.com/20703983/83270311-f4c45b00-a1d0-11ea-8a9b-d345a08e9f95.png)

**Comment by rp181135198** [comment]
@dbrova15 Have you found any solution?
I was reading godot official [docs](https://docs.godotengine.org/en/2.1/classes/class_globals.html) and found that `Globals` was availible in godot v2.1 but in godot v3.x, it is removed.

**Comment by DrMoriarty** [comment]
Plugin updated and using now new plugin management system.
